### ISSUE TITLE
Hey, kind of a noob question but I am new to this. What should my app code look like? I am not really sure what to make it. Thanks.

### ISSUE THREAD

**Issue by TheBigRedMugs** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#19]
Hey, kind of a noob question but I am new to this. What should my app code look like? I am not really sure what to make it. Thanks.

**Comment by Seems2Legit** [comment]
Just use a random code e.g. you can generate one here https://passwordsgenerator.net. c:
