### ISSUE TITLE
could u add get user's avater?

### ISSUE THREAD

**Issue by Monodesu** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#21]
i want get the avatar but i dont know how to modify the code :((

**Comment by Monodesu** [comment]
also how to get the lastest operators list

**Comment by sidelux** [comment]
User propic is in Ubisoft Api, not in R6 api.
For operators you could call getOperators.php and elaborate in your code.

**Comment by Monodesu** [comment]
https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/issues/23
sloved!
