### ISSUE TITLE
WAMP server

### ISSUE THREAD

**Issue by RedCoyoteOne** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#26]
hey,
i download your project and uploaded to my local server environment (i use wamp). the problem
when i want to display my user info it come with a issue.

**URL**
>localhost/getUser.php?name=ALC0N.&platform=uplay&appcode=tester01

**Result**
>{"players":{"ALC0N.":{"nickname":"ALC0N.","error":{"message":"User not found!"}}}}

But when i upload to my online hosting space it work.

i'm asking u is there any solution to the my local server environment.

**Comment by sidelux** [comment]
Check apache error log and if all wamp components are up to date.

**Comment by sidelux** [comment]
Closed due to inactivity.
