### ISSUE TITLE
getUser does not work with spaced nicknames

### ISSUE THREAD

**Issue by oa1907** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#29]
hello, as the title suggest: php version doesn't work with spaced nicknames.

for example;
nickname: oa1907 (my psn account and it has no space)
url: getUser.php?appcode=test&platform=psn&name=oa1907 
WORKS WELL

BUT
nickname: Search Meh Up
url: getUser.php?appcode=test&platform=xbl&name=SEARCH%20MEH%20UP
DOES NOT WORK!
"error":{"message":"User not found!"}}}}

**Comment by sidelux** [comment]
Ok i solved it and submitted for pull approval.
Meanwhile you can fix bu yourself by editing ubiApi.php and adding this line above line 43:
`$content = urlencode($content);`
So it becomes:
```
if($mode == 1 || $mode == "bynick"){
    $content = urlencode($content);
    $request_url = $prefixUrl."nameOnPlatform=".$content."&platformType=$platform";
}
```

**Comment by oa1907** [comment]
> Ok i solved it and submitted for pull approval.
> Meanwhile you can fix bu yourself by editing ubiApi.php and adding this line above line 43:
> `$content = urlencode($content);`
> So it becomes:
> 
> ```
> if($mode == 1 || $mode == "bynick"){
>     $content = urlencode($content);
>     $request_url = $prefixUrl."nameOnPlatform=".$content."&platformType=$platform";
> }
> ```

it works thanks
