### ISSUE TITLE
More stats and leaderboards

### ISSUE THREAD

**Issue by oa1907** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#31]
- previous seasons ranks and points
- leaderboards
- profile pictures
- k/d and w/l ratios per 5 days

**Comment by sidelux** [comment]
1. Previous rank data are in getUser:
https://pastebin.com/ti1wXAa8
See for past_seasons_wins, previous_rank_mmr, past_seasons_losses, past_seasons_abandons

2. Leaderboard, what do you search for? A **global** leadeboard? Alternatively you should save data in your database then make a leaderboard

3. User profile picture is inside Uplay Api, not in Rainbow 6 Api

4. That data are not stored in Ubi api, you can only get a "snapshot" of a stats, so you should save in your database then make averages, sums, graphics, etc..

**Comment by oa1907** [comment]
1. i mean last 4 or 5 seasons ranks

for example
grim sky
para bellum
chimera

etc. about last 3 4 seasons


2. i mean global leaderboard

**Comment by sidelux** [comment]
Uhm, do you know if there are some endpoints for that stats?

Meanwhile we can wait some other answers (@Seems2Legit)

**Comment by MarvinBost** [comment]
there is no ratio: victory / defeat
or ratio: killed / dead?

**Comment by sidelux** [comment]
Yes but is bugged, you should make manual division

**Comment by oa1907** [comment]
i mean i only get previous season ( if we are in season x we only get season x-1s data)

but i want to get too many past seasons data

**Comment by sidelux** [comment]
@oa1907 I think you can't without specific endpoint

**Comment by oa1907** [comment]
i dont understand what you say specific endpoint??

**Comment by sidelux** [comment]
For example `https://api-ubiservices.ubi.com/v2/profiles?"nameOnPlatform=nickname&platformType=plat` is a searchUser endpoint, there are so many different for Stats, Operators, etc. but we don't know if there are for previous Rank.

**Comment by oa1907** [comment]
ok i understood

**Comment by Seems2Legit** [comment]
The problem with Season 1-5 is Uplay fault (as @sidelux said), can't really do anthing about it ^^...
