### ISSUE TITLE
need stats ranked

### ISSUE THREAD

**Issue by MarvinBost** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#35]
i trying : &stats=ranked_pvp but is not working
         "rankedpvp_matchwon":126,
         "rankedpvp_kills":723,
         "rankedpvp_death":773,
         "rankedlpvp_matchlost":130,
         "rankedpvp_matchplayed":256,
         "rankedpvp_timeplayed":204662,

**Comment by sidelux** [comment]
`ranked_pvp` is not a valid stats, what are you looking for?

**Comment by MarvinBost** [comment]
i search ranked stats, like this 
ranked kills
ranked deaths
ranked win
ranked losses
ranked played
ranked time play

**Comment by sidelux** [comment]
I see that you have found these stats...
I don't understand.
Explain better what you trying to do with parts of your code.

**Comment by MarvinBost** [comment]
I did not find these statistics on your API, does it exist?
this feature exists or i need coding this ?

**Comment by sidelux** [comment]
You can get all stats that you need.
Here an example: http://fenixweb.net/r6api/getStats.php?name=Sidelux00&platform=uplay&appcode=r6apitelegram

**Comment by MarvinBost** [comment]
me i have :

casualpvp_death: 11465,
casualpvp_kills: 12038,
nickname: "username",
profile_id: "",
platform: "uplay"

is a new version ? i have installing this api before the fix ubisoft

**Comment by sidelux** [comment]
Ok, open `config.php` and in `default-stats` put: 
`casualpvp_death,casualpvp_kills`

Is not a new version, but last update support Nomad and Kaid operators, Ubi bug was server-side.

**Comment by MarvinBost** [comment]
ok, i add my stats with https://gist.github.com/LaxisB/3924cfdc35562b719d1c891cdb895366 ?
Thanks for reply

**Comment by sidelux** [comment]
Yes but not all are working, try.
