### ISSUE TITLE
Ubi API returns 400

### ISSUE THREAD

**Issue by scrouthtv** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#36]
Are there any online resources on how to use Ubisoft's API?

Because I tried implementing your code in Java and started with the login functionality, but the server always returns 400 (Bad Request). You can check out my code over at https://github.com/scrouthtv/R6StatsAPI. 

I used your method to contact Ubi Servers and login (had to change something with the content length, but that should work). Do you have an idea, why your code works for me, but my implementation doesn't?

Thanks in advance.

**Comment by Talli0n** [comment]
I dont think this is...

**Comment by sidelux** [comment]
Short answer: no.

Btw i suggest you to read carefully headers and access token, then with debugging you should solve your problem.
