### ISSUE TITLE
Get K/D & W/L  

### ISSUE THREAD

**Issue by AlizBakhshi** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#37]
How Can Get K/D and W/L ?

**Comment by sidelux** [comment]
With divisions.
So rankedpvp_matchwon/rankedpvp_matchlost for W/L
and rankedpvp_kills/rankedpvp_death for K/D

**Comment by AlizBakhshi** [comment]
which file can get rankedpvp_kills/rankedpvp_death ?

**Comment by sidelux** [comment]
getStats.php
with GET param "stats" = rankedpvp_kills, rankedpvp_death
So: `getStats.php?name=Sidelux&platform=uplay&appcode=youcode&stats=rankedpvp_kills, rankedpvp_death`
