### ISSUE TITLE
Missing name in getOperators

### ISSUE THREAD

**Issue by nasourso** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#38]
If you use getOperators Tachanka does not have a name set.

**Comment by sidelux** [comment]
What is your url call?
Paste it (without appcode)

**Comment by nasourso** [comment]
https://website.com/api/r6/getOperators.php?id=a39c7ad5-3282-467c-bc85-f65b0e61cde4&appcode=test

object		{2}
==players		{1}
====[...]
==operators		{44}
====capitao		{6}
====[...]
====thermite		{6}
====tachanka		{4} **<-- Only 4 elements**
======images		{3} 
======category	:	def
======index	:	5:4
======id	:	tachanka **<-- No name and organisation**
====blackbeard		{6}
====buck		{6}  **<-- Always 6 elements**
====frost		{6}
======images		{3}
======category	:	def
======index	:	3:6
======id	:	frost
======organisation	:	JTF2 **<-- Frost has an organisation**
======name	:	Frost  **<-- Frost has a name**
====[...]

**Comment by sidelux** [comment]
Fixed in next release
