### ISSUE TITLE
Some stats not displayed

### ISSUE THREAD

**Issue by sidelux** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#4]
Hi, i have a config file:

```
<?php

$config = array(
	"appcode" => "xxx",
	"ubi-email" => "xxx",
	"ubi-password" => "xxx",
	"default-region" => "emea",
	"default-stats" => "progression_level,progression_xp,rankedpvp_matchwon,rankedpvp_matchlost,rankedpvp_matchwlratio,rankedpvp_kills,rankedpvp_death,rankedpvp_kdratio,rankedpvp_timeplayed,casualpvp_death,casualpvp_kdratio,casualpvp_kills,casualpvp_matchlost,casualpvp_matchplayed,casualpvp_matchwlratio,casualpvp_matchwon,casualpvp_timeplayed,generalpve_revive,generalpvp_suicide,generalpvp_reinforcementdeploy,generalpvp_barricadedeployed,generalpvp_bulletfired,generalpvp_bullethit,generalpvp_meleekills,generalpvp_penetrationkills,weapontypepvp_killassists"
	// all stats: https://gist.github.com/LaxisB/3924cfdc35562b719d1c891cdb895366
);

?>
```

With lots of stats, but when i call your api i show only a part of that stats:

```
{  
   "players":{  
      "40078dc7-5f24-49a6-ad27-070c9c528f6c":{  
         "casualpvp_matchwon":225,
         "generalpvp_reinforcementdeploy":4735,
         "generalpvp_barricadedeployed":2379,
         "rankedpvp_timeplayed":771465,
         "generalpvp_penetrationkills":247,
         "rankedpvp_death":2842,
         "generalpvp_bullethit":33688,
         "generalpvp_suicide":9,
         "generalpvp_meleekills":8,
         "generalpvp_bulletfired":73879,
         "casualpvp_matchplayed":513,
         "casualpvp_death":1598,
         "generalpve_revive":17,
         "casualpvp_kills":1067,
         "rankedpvp_matchlost":320,
         "casualpvp_matchlost":288,
         "rankedpvp_matchwon":307,
         "casualpvp_timeplayed":417366,
         "rankedpvp_kills":1923,
         "nickname":"Sidelux00"
      }
   }
}
```

I have made a mistake or there are some problems?

**Comment by JulianGassner** [comment]
We are investigating that issue. Please stand by

**Comment by JulianGassner** [comment]
It looks like it's a ubisoft limit. We are working on a workaround

**Comment by Seems2Legit** [comment]
Fixed it with array_chunk (ubi limited it to max 20 stats per request...)

**Comment by sidelux** [comment]
@Seems2Legit Thanks :D

**Comment by Seems2Legit** [comment]
Np :D But i think i fucked up... because its actually 19 not 20. So if you already downloaded the new version you meight need to change that in the UbiAPI.php

**Comment by sidelux** [comment]
Don't worry, just push in your repo ;)

**Comment by sidelux** [comment]
I tried but now it prints only 19 stats despite 30+ i put in config files (for example progression_level).
Am i wrong?

**Comment by Seems2Legit** [comment]
Wait im checking that...

**Comment by Seems2Legit** [comment]
`{
    "player_profiles": [
        {
            "xp": 5858,
            "profile_id": "09ef2790-ee5a-4909-b9dc-4e4042dbed7d",
            "lootbox_probability": 4150,
            "level": 284
        }
    ]
}`
You want this right?

**Comment by Seems2Legit** [comment]
7 stats in your config don't seem to work... but I dont know why

**Comment by Seems2Legit** [comment]
Also, every stat with ratio in it won't work.

**Comment by Seems2Legit** [comment]
You might have to calculate those ratios yourself...

**Comment by sidelux** [comment]
Maybe can help: https://ubistatic-a.akamaihd.net/0058/prod/assets/data/statistics.definitions.eb165e13.json

Btw why progression_level not working?

**Comment by Seems2Legit** [comment]
Yeah, that's what I meant to say:
`{ "player_profiles": [ { "xp": 5858, "profile_id": "09ef2790-ee5a-4909-b9dc-4e4042dbed7d", "lootbox_probability": 4150, "level": 284 } ] }`
I'll add it tomorrow.
Should I add a parameter for this because it'll take more time to load? (Moved the issue #8)
