### ISSUE TITLE
getSmallUser.php does not return expected data format

### ISSUE THREAD

**Issue by deadhead1316** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#42]
getSmallUser.php return's json format like this - 
[
    uid{
              uid : id
              nick : nickname
          }
]
but the readme states that the data should be like this - 
[
        {
              uid : id
              nick : nickname
         }
]
As a result I can't access the array when searched by nickname because uid itself is a variable.

**Comment by sidelux** [comment]
Fixed in the next release, anyway for example in javascript you can do something like this:
```
var keys = Object.keys(objResp.players);
var ubi_id = keys[0];
console.log(objResp.players[ubi_id]);
```
