### ISSUE TITLE
(Possibly Just Stupid) White Page when Accessing

### ISSUE THREAD

**Issue by MayhemBill** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#47]
I just recently got this running, and whenever I open the page, with app code and user id, its blank, with no data.

**Comment by sidelux** [comment]
What error do you get in your webserver log?

**Comment by MayhemBill** [comment]
okay that was an issue on my end, php wasn't configured for curl support, but now it returns {error: true}

**Comment by MayhemBill** [comment]
That was an issue on my end, curl was not properly supported, and I failed to check the logs
