### ISSUE TITLE
UBIAPI Login not working

### ISSUE THREAD

**Issue by hadouken111** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#49]
Hello, I'm trying to use your Ubi API , but it seems to have a problem when login is called, i get an error **404 File or diretory not found.
The ressource you are looking  for might have been removed, had its name changed, or its temporarily unavailable.**

it seems the URL _"https://connect.ubi.com/ubiservices/v2/profiles/sessions"_ is no longer good and that Ubisoft is maybe changed this url can you please help me to correct this problem.
Thank you

**Comment by sidelux** [comment]
We are checking the problem, maybe is a temporary maintenance.

**Comment by hadouken111** [comment]
oh ok, if that helps you it doesn't work since 2020-01-21 10:49am (or 21-01-2020 10H49), 
could you keep me informed if you advance on the problem. 
Thank you :)

**Comment by sidelux** [comment]
Seems that uplay have [some problems](https://downdetector.com/status/uplay/), maybe after fix the api will work.

**Comment by hadouken111** [comment]
ok thank you for your return, so we just need to wait for Uplay be operational again :/

**Comment by oa1907** [comment]
url changed or servers at maintenance?

**Comment by oa1907** [comment]
i dont think like u. probably they changed url. because all ubi sites using api like us and i can see my stats on r6 official site easily. What about this??

**Comment by sidelux** [comment]
Fixed, i will push the update in minutes.

**Comment by hadouken111** [comment]
@sidelux :) what's finally the problem ? they change they URL ?

**Comment by sidelux** [comment]
See #51

**Comment by sidelux** [comment]
See #51

**Comment by hadouken111** [comment]
Thank you bro, now it works GJ  :)
