### ISSUE TITLE
Added support for $platform

### ISSUE THREAD

**Issue by sidelux** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#5]
I have added support for platforms specification, perfectly backward compatible (99%).
If you are interested, how can you send the new code?
I hope to help someone with that improvement.

Example:
`http://website.net/api/getStats.php?name=yyy&platform=psn&appcode=xxx`

Thanks for reading :)

**Comment by Giggitybyte** [comment]
This is what I've been waiting for! (See #2)
You need to create a [pull request](https://help.github.com/articles/creating-a-pull-request/).

**Comment by sidelux** [comment]
I have updated getRanking, getStats and searchUser with respective php file, and some little fix to syntax.
I will send a pull request in a short time.

**Comment by Seems2Legit** [comment]
Wow... didn't see that. Fixed it myself. But thank you anyways 👍.
