### ISSUE TITLE
UBI url error 

### ISSUE THREAD

**Issue by hadouken111** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#54]
Hello, I'm using your Ubi API , but it seems to have a problem when login is called, i get an error 404 File or diretory not found.
The ressource you are looking for might have been removed, had its name changed, or its temporarily unavailable.

it seems the URL is no longer good and that Ubisoft is maybe changed this url can you please help me to correct this problem.

**Comment by sidelux** [comment]
According to [Ubi's last tweet](https://twitter.com/Ubi_Fanch/status/1240984808748130304), Ubi has temporary removed Api access.

**Comment by hadouken111** [comment]
Thank you for your return. I had not seen that the stats was deactivated, does it come from the current state of the situation with the covid-19? can we expect a return of the stats and when? or is it final?

**Comment by sidelux** [comment]
Yes it's caused by high traffic volumes.
Currently they not have an ETA to reactivate, probably at the end of the covid situation.
