### ISSUE TITLE
where can i get the appcode?

### ISSUE THREAD

**Issue by honkkki** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#56]

**Comment by honkkki** [comment]
"message": "Invalid credentials",
    "errorCode": 3,
    "httpCode": 401,

because of my ubi account or password wrong?

**Comment by sidelux** [comment]
It's your security code for validate requests, so you have to decide by yourself.

**Comment by sidelux** [comment]
> "message": "Invalid credentials",
> 
>     "errorCode": 3,
> 
>     "httpCode": 401,
> 
> 
> 
> because of my ubi account or password wrong?

Yes

**Comment by honkkki** [comment]
> > "message": "Invalid credentials",
> > ```
> > "errorCode": 3,
> > 
> > "httpCode": 401,
> > ```
> > 
> > 
> > because of my ubi account or password wrong?
> 
> Yes

can i get user profile avatar?

**Comment by sidelux** [comment]
I think not, there is specific uplay apis to get that.
Anyway you can use system like [r6checker](https://github.com/AdrianR25/r6checkerapi) to do that.
