### ISSUE TITLE
Get Xbox Avatar

### ISSUE THREAD

**Issue by hadouken111** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#57]
Hi, 
I would like to know how we can recover the Xbox avatar of the player visibly this is possible because tracker does it, but I do not understand how
there is an example of url : 
https://avatar-xbl.tracker.gg/image.png?url=wHwbXKif8cus8csoZ03RWwcxuUQ9WVT6xh5XaeeZD02wEfGZeuD.XMoGFVYkwHDqZ7meh_qT0.q8jCBFEmlLUUycH0Fgde2AEzGFjbqn5TcoLxeC4UsCwD4SOvyj.Rc0cXyVE8atLZHaIv3L9EPZ68cGqoA9LskimlLUV.FrP1c-

Thank for your help :)

**Comment by sidelux** [comment]
If you need Xbox avatar maybe you can use [this method](https://stackoverflow.com/a/9772451/7126704).

**Comment by hadouken111** [comment]
Thank you for your return, but this is the avatar of the Xbox account, but I want the Uplay avatar of Xbox players

**Comment by sidelux** [comment]
So basically you need the uplay avatar (dot).
You will build something like this URL
https://ubisoft-avatars.akamaized.net/40078dc7-5f24-49a6-ad27-070c9c528f6c/default_256_256.png

The **40078dc7-5f24-49a6-ad27-070c9c528f6c** part is the Ubi profile_id, to get that you should make a POST request with this header:
```
authorization:Basic (base64 of user + ":" + password)
Content-Type:application/json
Ubi-AppId:39baebad-39e5-4552-8c25-2c9b919064e2
```

Then you'll get a json with:
`"profileId": "40078dc7-5f24-49a6-ad27-070c9c528f6c",`

Enjoy

**Comment by hadouken111** [comment]
I Already try this link but it works only with PC account 
I use https://ubisoft-avatars.akamaized.net for PC account
I use for PS4 account https://avatar-cdn.tracker.gg/api/avatar/2/
and for Xbox I found this link https://avatar-xbl.tracker.gg/image.png?url=
but I don't understand the URL parameter, or find it how is it formatted ??

**Comment by sidelux** [comment]
So try with https://github.com/Tabwire/TheDivisionTab-API

**Comment by hadouken111** [comment]
Still not working :/

**Comment by Seems2Legit** [comment]
@hadouken111 you need the user_id. I'll add it to the response.

**Comment by Seems2Legit** [comment]
(On pc the profile_id and the user_id are the same, but on other platforms, you'll need the user_id to get their avatar)

**Comment by hadouken111** [comment]
@Seems2Legit Thanks for your comments, now it works i was using profil_id and not user_id :)
