### ISSUE TITLE
[SOLUTION] Cav stats won't work + get season name + max rank info(name, icon)

### ISSUE THREAD

**Issue by oa1907** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#58]
There's an index issue for operator cav. When api gets index it returns 1:8, but api gets value it returns 3:8 

+ get season name when getUser calls
+ get max rank info when getUser calls

[SOLUTION.zip](https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/files/4673885/SOLUTION.zip)

**Comment by sidelux** [comment]
Thanks, we will push a fix.
