### ISSUE TITLE
"All Stats" link returns error 404 on GitHub

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#63]
The link in config.php which shows all available stats to request no longer exists. When clicking the link, it takes you to GitHub's error 404 page.
https://gist.github.com/LaxisB/3924cfdc35562b719d1c891cdb895366

**Comment by sidelux** [comment]
We will update that link soon.
Meanwhile you can use this: https://gist.github.com/sidelux/c2724e64acb7e1b8921c11572800f8d4
