### ISSUE TITLE
getUser.php returning default values when season parameter is < 18

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#67]
I'm noticing that when the season parameter in the url is not 18 or 19, every value shows as 0, unranked, etc. Any known cause for this? Thanks.

**Comment by sidelux** [comment]
For me it works from season 6 to 19 (< 6 are not provided by Ubi), probably you write username and platform wrong or could be a Ubi issue.

**Comment by Techmo9j** [comment]
I just cloned the whole repo to make sure everything was up to date: Look at this:
https://jarrenmorris.com/r6/getUser.php?name=guccigangsespr&platform=psn&appcode=b2i37-tr8fn-dwkjh-g2378-gh8q4&season=17

But then try switching the season parameter to 18 or 19.

On Oct 12, 2020, at 11:49 PM, Edoardo Cortese <notifications@github.com> wrote:

﻿

For me it works from season 6 to 19 (< 6 are not provided by Ubi), probably you write username and platform wrong or could be a Ubi issue.

**Comment by sidelux** [comment]
Uhm maybe there are troubles with psn stats or similar, i'll try to investigate.

**Comment by Techmo9j** [comment]
Any word yet?

On Oct 13, 2020, at 7:25 AM, Edoardo Cortese <notifications@github.com> wrote:

﻿

Uhm maybe there are troubles with psn stats or similar, i'll try to investigate.

**Comment by Techmo9j** [comment]
Adding onto this issue. When the platform parameter is Uplay, and the season parameter is anywhere between 6 and 13, the kills and deaths always return 0, but every other stat appears. PSN & XBL return 0 for every stat on seasons 6 to 17.

**Comment by sidelux** [comment]
This is very strange, we not manipulate datas based on season value... We will investigate more.

**Comment by Techmo9j** [comment]
How's the investigating going?

**Comment by sidelux** [comment]
No news, i'm sorry.

**Comment by Techmo9j** [comment]
Do most apps/websites use the same Ubisoft API? Because it's not a problem on any of them. Is it possible that seasons 6-17 don't exist in the Ubisoft database, but rather as a different number, or season title? And then from season 18, onward, they switched to a number-based system corresponding to the season in order from game-launch. I'll help you with this assuming it's not just a PHP problem. Do you have a link to the Ubisoft API Documentation?

**Comment by sidelux** [comment]
All use the same, there is only one API. Seasons exists cause i show the correct datas, and have a numerical parameter.
A link to official documentation does not exists, you can only try to understand by yourself.

**Comment by Techmo9j** [comment]
UPDATE: Switching region from emea to ncsa shows every season but the kills and deaths still show as 0.

**Comment by Techmo9j** [comment]
From Season 6-13, showing 0 for kills and deaths ^
