### ISSUE TITLE
Error 403 Forbidden 

### ISSUE THREAD

**Issue by Zoogoumafou** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#68]
Can some can help me whit this error ?
![Capture](https://user-images.githubusercontent.com/72103617/96747393-3a5b0d80-1396-11eb-89c9-a5ca43225853.PNG)

**Comment by sidelux** [comment]
It's an error caused by new ubisoft stats website, we are working on a solution.

**Comment by Zoogoumafou** [comment]
ho well... we will wait.

**Comment by Zoogoumafou** [comment]
I dont know if something change since yesterday on ubisoft side, but the error are not the same, no more 403 error. Only invalide args, and undefined offset.

**Comment by sidelux** [comment]
I get 403 as yesterday, i tried to look inside new page's code but i can't find operators.json or similar for now :/

**Comment by Zoogoumafou** [comment]
Can we do a version whit out operators.js ?

**Comment by sidelux** [comment]
We should need that infos to build operators list, i'll keep an eye if there will be another method.

**Comment by Zoogoumafou** [comment]
I mean, if i try to remove the part of the operator to get an answer whitout the operator list, because in my project i only need Alias and amout of match played, kill and death of each season, should works ?

**Comment by sidelux** [comment]
Yes, you need to comment 3rd line of `UbiApi.php`.

**Comment by Zoogoumafou** [comment]
Good thank you, i do not have error code anymore, but everyone is user not found.

**Comment by sidelux** [comment]
That works for me, check for your region and platform.

**Comment by Zoogoumafou** [comment]
what ever i try dont works. 

I saw we supposed to give 777 for api_ticket.
I gave made it writable, read and executable from everyone in windows, i dont know if my probleme cam from there

**Comment by sidelux** [comment]
Check for your web services log, you should see if it is not able to write on it or other errors.

**Comment by Zoogoumafou** [comment]
the logs show me nothing about api_ticket, i dont know where that probleme form

**Comment by Zoogoumafou** [comment]
Btw, its normal what ever i put in 
`"ubi-email" => "",
	"ubi-password" => "",`
give me the same result, no error...

**Comment by Zoogoumafou** [comment]
api ticket is not the probleme btw..

**Comment by Zoogoumafou** [comment]
I got new probleme
