### ISSUE TITLE
getOperators doesn't work

### ISSUE THREAD

**Issue by oa1907** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#69]
... operators":[]}

**Comment by Zoogoumafou** [comment]
They are working on it

**Comment by oa1907** [comment]
any progress?

**Comment by sidelux** [comment]
Until ubi publish operators json list or something similar we can't populate that value...

**Comment by oa1907** [comment]
> Until ubi publish operators json list or something similar we can't populate that value...

https://www.instagram.com/p/CHYLBOShfJt/

check out this post.
seems like ubi changed something. stats page reworked.
rainbow6.com/stats

**Comment by sidelux** [comment]
Exactly, that is the cause of Operators array is empty now.

**Comment by oa1907** [comment]
so, how do you find operator json?

**Comment by sidelux** [comment]
In the past website version we got from scraping some pages, now i can't find it and other website stats have the same problem, so for now i don't know how to get it automatically.

**Comment by Seems2Legit** [comment]
@oa1907 you can use this unofficial endpoint for now: https://api.statsdb.net/r6/config

**Comment by sidelux** [comment]
Just pulled a new commit to implement your temporary endpoint.
