### ISSUE TITLE
{error:true} ?

### ISSUE THREAD

**Issue by Zoogoumafou** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#70]
Yeah, i have set up everything everywhere and now i got this page when i try to do a request. Nothing in error.log
{error:true}

**Comment by sidelux** [comment]
Can you share your config (without user and psw) and check for ticket file permission?

**Comment by CarterGunale** [comment]
I got the same question on my server but on my PC it's okey.
my config:
$config = array(
	"appcode" => "thisisthecode",
	"ubi-email" => "***",
	"ubi-password" => "***",
	"default-region" => "apac", // Regions: emea - ncsa - apac 
	"default-stats" => "generalpvp_timeplayed,generalpvp_kills,generalpvp_death,generalpvp_matchplayed,generalpvp_matchwon", // All stats: https://gist.github.com/sidelux/c2724e64acb7e1b8921c11572800f8d4
	"default-platform" => "uplay", // Platforms: uplay - xbl - psn
	"default-progression" => "true", // Enabled: true - false
    'rank-images-png' => false // Rank image format: svg or png? Default: false -> svg
);
