### ISSUE TITLE
"User not found!" error sometimes when the user does exist.

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#73]
I have an iOS app using this API. Very often, since the last update to the source code of this project, my app will be unable to get the stats and all that is returned is the JSON structure of { error: { message: "User not found!" } }. However, I can't reproduce this issue by using the API in a browser.

I don't see how it could be an issue in my app because it IS reading the data from the API, but the API is only returning an error message.

But I also don't see how it could be an issue on the API-Wrapper's end because it's just the middleman in getting the data from Ubi and translating it into raw JSON.

Any idea what's up?

**Comment by sidelux** [comment]
Can you provide username and platform where you get this error?

Probably some params (like spaces for xbox or generally special chars) are passed without encoding or something similar i think.

**Comment by Techmo9j** [comment]
It's any username and any platform. Like you would look it up in my app 2-3 times and get that error, then maybe the 4th time, it works. I have it printing the JSON every time it fails and it just shows that error structure.

**Comment by Techmo9j** [comment]
It's the same usernames and platforms that worked fine before this update to the source code.

**Comment by sidelux** [comment]
You mean after this pull?
https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/pull/72

Check also the apache logs.
