### ISSUE TITLE
Aruni + Zero stats in getStats.php

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#74]
Is there an updated version of: https://gist.github.com/sidelux/c2724e64acb7e1b8921c11572800f8d4
that includes stats for the ops Zero and Aruni?

**Comment by sidelux** [comment]
There is not operator abilities data in that file, you should discover it by making requests to getOperators.

**Comment by Seems2Legit** [comment]
I'm currently working on it. I'll keep you updated.

**Comment by Seems2Legit** [comment]
@Techmo9j are you sure that Zero stats aren't working with the newest version?

**Comment by Seems2Legit** [comment]
https://api.statsdb.net/r6/config has been updated. Aruni is now available. The index is pure speculation because I can't 100% confirm that it's the correct index but it's very likely. (Ubisoft doesn't use the index system anymore so you can't find anything on their website)
