### ISSUE TITLE
Operator API offline?

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#76]
getOperators.php is returning an empty array.

**Comment by sidelux** [comment]
Maybe another change of Ubi's api, we'll checking it...

**Comment by sidelux** [comment]
Checked and statsdb's api has been protected with authorized access ([check here](https://api.statsdb.net/r6/config)).
You can temporary fix by updating `Operators.php` line 10 by replacing url with `https://pastebin.com/raw/hA1tnH4G`.
And commenting/removing line 13.

**Comment by Seems2Legit** [comment]
https://api.statsdb.net/r6/config is working again

**Comment by sidelux** [comment]
Perfect!
