### ISSUE TITLE
not responding with stats

### ISSUE THREAD

**Issue by hdhdhfhfirjf** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#77]
set up the api on my website changed the config and im getting this response not quite sure why maybe i fucked something up 

![image](https://user-images.githubusercontent.com/65376762/107678560-8e517100-6c69-11eb-9d52-85d53adb5848.png)

**Comment by hdhdhfhfirjf** [comment]
i believe its because im looking for players in NA region and i cant figure out the region code

**Comment by Techmo9j** [comment]
Region codes are as follows:
ncsa - North Central South America
emea - Europe Middle East Africa
apac - Asia Pacific (Includes Oceania)
