### ISSUE TITLE
Loading all seasons at once

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#78]
Is it possible for you to develop a PHP file that would be the same as .../getUser.php?season=6 all the way through to the newest season at once? I'm trying to get a list of all the seasons stats at once but in order to do so, it's running that script like 14 times, each being a different season and it's causing my server to return a 508 error (exceeding resource limits).

**Comment by sidelux** [comment]
That would make the same requests as yours so will be the same thing...
