### ISSUE TITLE
[Not Issue] Question about operator indexes

### ISSUE THREAD

**Issue by Techmo9j** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#79]
I'm working on accessing the stats directly from Ubisoft from my iOS app and have successfully been able to GET the operator stats json. I notice it's not broken down to each operator but has an index type of thing after the stat name, like :4:E. I was trying to analyze your code and see if I could figure out how it sorts those into a list of operators and I was unable to.

Can you please explain how the operator stats indexes are converted into operator names?

Thanks.

**Comment by Seems2Legit** [comment]
Hi there, before Ubisoft reworked their stats website you were able to load a JSON from there containing all the indices and so on. Nowadays I'm not quite sure how to figure out which index belongs to which operator. I waited until the new season/operator had been released and searched for new indices in the response.

**Comment by Techmo9j** [comment]
Hello,
I'm not sure I understand fully because in your getOperators.php script, it returns a json of the operators sorted in an array with each operator name as the key. How are you converting the ubisoft json with indices to the json returned in getOperators.php?

**Comment by Seems2Legit** [comment]
The getOperators.php uses the config endpoint of StatsDB [https://api.statsdb.net/r6/config](url)

**Comment by Techmo9j** [comment]
Ohhh okay. I'll play around with that. Thanks
