### ISSUE TITLE
HELP WANTED – Endpoint for Ranked 2.0 & Operation: Solar Raid

### ISSUE THREAD

**Issue by SwiftCODA** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#91]
The XHR requests on the Ubisoft stats tracker website are making requests for all 28 seasons, and returning data for all except 28, the current one. Does anyone know of a new endpoint for seasonal ranked stats with skill / rank value / hidden mmr and whatever else they added in the Ranked 2.0 update?

Information:
Ubisoft Web Stats XHR/Fetch Requests:
`player_skill_records`:
  `method`: `GET`
  `host`: `public-ubiservices.ubi.com`
  `path`: `/v1/spaces/05bfb3f7-6c21-4c42-be1f-97a33fb5cf66/sandboxes/OSBOR_PS4_LNCH_A/r6karma/player_skill_records`
  `parameters`:
  - `board_ids`: `pvp_ranked`
  - `season_ids`: `-1,-2,-3,-4,-5,-6,-7,-8,-9,-10,-11,-12,-13,-14,-15,-16,-17,-18,-19,-20,-21,-22,-23,-24,-25,-26,-27,-28` (-1 would be the current season, -2 would be the one before it, -28 would be Season 1.
  - `region_ids`: `ncsa`
  - `profile_ids`: `13a81b0c-1107-4449-8adb-9ae06c09d28a` (Random leaderboard player on PSN who has data for season 28)
  `headers`:
  - `Authorization`: `ubi_v1 t={MY_TOKEN}`
  - `User-Agent`: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15`
  - `Ubi-AppId`: `{MY_UBI_APP_ID}`
  - `Ubi-SessionId`: `{MY_UBI_SESSION_ID}`
  - `Connection`: `keep-alive`
  `response`:
(An array of object like this one. The `-1` season corresponds to this object)
```json
{
   "season_id":27,
   "regions_player_skill_records":[
      {
         "region_id":"ncsa",
         "boards_player_skill_records":[
            {
               "board_id":"pvp_ranked",
               "players_skill_records":[
                  {
                     "max_mmr":0,
                     "skill_mean":25,
                     "deaths":0,
                     "profile_id":"13a81b0c-1107-4449-8adb-9ae06c09d28a",
                     "next_rank_mmr":0,
                     "rank":0,
                     "max_rank":0,
                     "board_id":"pvp_ranked",
                     "skill_stdev":8.334,
                     "kills":0,
                     "last_match_skill_stdev_change":0,
                     "past_seasons_wins":0,
                     "update_time":"1970-01-01T00:00:00+00:00",
                     "last_match_mmr_change":0,
                     "abandons":0,
                     "season":27,
                     "past_seasons_losses":0,
                     "top_rank_position":0,
                     "last_match_skill_mean_change":0,
                     "mmr":2500,
                     "previous_rank_mmr":0,
                     "last_match_result":0,
                     "past_seasons_abandons":0,
                     "wins":0,
                     "region":"ncsa",
                     "losses":0
                  }
               ]
            }
         ]
      }
   ]
},
{
   "season_id":-28,
   "regions_player_skill_records":[]
}
```
It appears the server is seeing a request for stats for the season which was 27 seasons ago (`-28`), and saying "hmm... we don't have stats for a season this far back", which makes sense, considering that `-1` returns season 27, and not 28.

This proves that the `player_skill_records` endpoint's data source does not contain information for season 28.

The other request made:
`players`:
  `method`: `GET`
  `host`: `public-ubiservices.ubi.com`
  `path`: `/v1/spaces/05bfb3f7-6c21-4c42-be1f-97a33fb5cf66/sandboxes/OSBOR_PS4_LNCH_A/r6karma/players`
  `parameters`:
  - `board_id`: `pvp_ranked`
  - `season_id`: `-1` (Should return the current season, 28)
  - `region_id`: `ncsa`
  - `profile_ids`: `13a81b0c-1107-4449-8adb-9ae06c09d28a`
  `headers`:
  - `Authorization`: `ubi_v1 t={MY_TOKEN}`
  - `User-Agent`: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.1 Safari/605.1.15`
  - `Ubi-AppId`: `{MY_UBI_APP_ID}`
  - `Ubi-SessionId`: `{MY_UBI_SESSION_ID}`
  - `Connection`: `keep-alive`
  `response`:
```json
{
   "players":{
      "13a81b0c-1107-4449-8adb-9ae06c09d28a":{
         "max_mmr":0,
         "skill_mean":25,
         "deaths":0,
         "profile_id":"13a81b0c-1107-4449-8adb-9ae06c09d28a",
         "next_rank_mmr":0,
         "rank":0,
         "max_rank":0,
         "board_id":"pvp_ranked",
         "skill_stdev":8.334,
         "kills":0,
         "last_match_skill_stdev_change":0,
         "past_seasons_wins":0,
         "update_time":"1970-01-01T00:00:00+00:00",
         "last_match_mmr_change":0,
         "abandons":0,
         "season":27,
         "past_seasons_losses":0,
         "top_rank_position":0,
         "last_match_skill_mean_change":0,
         "mmr":2500,
         "previous_rank_mmr":0,
         "last_match_result":0,
         "past_seasons_abandons":0,
         "wins":0,
         "region":"ncsa",
         "losses":0
      }
   }
}
```
Notice the "season" value is `27`, even though we passed in `-1` to fetch the *current season*, `28`.

This proves that the `players` endpoint's data source does not contain information for season 28.

EDIT:
The original endpoints we were using before Neon Dawn for seasonal data do not work for season 28 either.
<img width="1010" alt="Screen Shot 2022-12-08 at 3 47 54 PM" src="https://user-images.githubusercontent.com/17557339/206590580-d32647dd-bbb3-4e3d-b262-dd1336b2ac6c.png">

**Comment by Us3r-3C29x** [comment]
https://tabstats.com/ has the data for season 28, so I dont know

**Comment by SwiftCODA** [comment]
> https://tabstats.com/ has the data for season 28, so I dont know

So does TRN. But yet the actual tracker on the Ubi site is broken. Empty arrays in the response and uncaught exception errors too. I will probably hop on the PC R6 and intercept the HTTP requests to see if there's anything new there...

**Comment by BadCoder1337** [comment]
While I have been trying to discover new endpoints I found an awesome [guide](https://github.com/YoobieRE/ubisoft-dmx-decode) for intercepting Ubisoft Connect network activity. But it doesn't work for game client since it utilizes a separate network stack over Winsock2. To intercept game client requests you should unpin SSL cert. It's possible with some Cheat Engine magic which I found here https://www.unknowncheats.me/forum/3113434-post11501.html. I'm read-only on the forum, so I can't contact the author.

**Comment by Us3r-3C29x** [comment]
Any updates?

**Comment by BadCoder1337** [comment]
Ubisoft re-enabled unique builds to prevent cheat development, and as a side effect, also my API research. I'm waiting for community to resolve this.

**Comment by Us3r-3C29x** [comment]
https://github.com/hmes98318/r6s-stats-api

He updated to rank 2.0, somebody may have a look on it. I dont currently have time

**Comment by BadCoder1337** [comment]
> https://github.com/hmes98318/r6s-stats-api
> 
> He updated to rank 2.0, somebody may have a look on it. I dont currently have time

He is fetching [r6.tracker.network](https://github.com/hmes98318/r6s-stats-api/blob/77543179e223dc3c1f3d6e8a6b825b3321562cb4/index.js#L23), which have received API endpoints from Ubisoft.
Relying on an additional 3rd party is not a solution.

**Comment by SwiftCODA** [comment]
> Ubisoft re-enabled unique builds to prevent cheat development, and as a side effect, also my API research. I'm waiting for community to resolve this.

Is this resulting in you not being able to sniff HTTPS requests? I attempted to use the Postman HTTPS interception tool last night and normal HTTPS traffic was working fine in browser, but the Ubisoft Connect app didn't like it.

We need to dedicate some time and resources to this as soon as possible. This is causing lots of downtime for my (and probably many of your guys) services and resulting in a loss of revenue.

Please share this issue around with people who can help out. Thanks, and good luck.

**Comment by SwiftCODA** [comment]
@Seems2Legit do you recall any methods you used way back in the beginning to find the endpoints you currently have coded?

**Comment by BadCoder1337** [comment]
> Is this resulting in you not being able to sniff HTTPS requests?

Again, you can't intercept game and Ubisoft Connect HTTPS queries with trivial mitm tools. Both use SSL pinning, but in various ways. For Ubisoft Connect you can dump keys from lsass.exe and decrypt packets in Wireshark. The game is using separate request library built with OpenSSL and Winsock.
When unique builds were activated I was unable to disable BattlEye to attach a debugger. Now I got a configuration to disable it so I can move forward.
I saw desired batch rank query paths, but still can't figure how to use it without a full request.

**Comment by SwiftCODA** [comment]
> I saw desired batch rank query paths, but still can't figure how to use it without a full request.

Would you be able to share any information you came / will come across here? I'm confident that we can come to a resolution if we all work together with little bits and pieces we find individually.

**Comment by floxay** [comment]
use `/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/sandboxes/OSBOR_XPLAY_LNCH_A/`

![image](https://user-images.githubusercontent.com/57007485/209000063-18b8b66b-66b9-46e5-8caf-b30dc929a9e9.png)

**Comment by danielwerg** [comment]
> use `/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/sandboxes/OSBOR_XPLAY_LNCH_A/`
> 
> ![image](https://user-images.githubusercontent.com/57007485/209000063-18b8b66b-66b9-46e5-8caf-b30dc929a9e9.png)

hmm, `mmr` and `max_mmr` value doesn't seem to much the ones from tabstats or r6.tracker for given profile. Also, do you happen to know how to get Rank Points value?

**Comment by BadCoder1337** [comment]
> use `/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/sandboxes/OSBOR_XPLAY_LNCH_A/`

This looks like an old ranked system running in parrallel with ranked 2.0.
I played 9 ranked matches and my rank is still zero (unranked), but I'm Copper 3 in terms of ranked 2.0.
Literally yesterday I discovered that there's a new spaceId for crossplay.
 
UPD: Confirmed. After 10th game I got Silver 3 with 2340 MMR. Just like the good old days.

**Comment by floxay** [comment]
New /looking, not sure how new these actually are/ endpoints are under /v2.

For example for profiles use
`https://public-ubiservices.ubi.com/v2/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/title/r6s/skill/full_profiles`

`profile_ids` and `platform_families` query params have to be specified for this endpoint.
<details><summary>Response</summary>

```json
{
    "platform_families_full_profiles": [
        {
            "board_ids_full_profiles": [
                {
                    "board_id": "casual",
                    "full_profiles": [
                        {
                            "profile": {
                                "board_id": "casual",
                                "id": "REMOVED",
                                "max_rank": 0,
                                "max_rank_points": 0,
                                "platform_family": "pc",
                                "rank": 0,
                                "rank_points": 0,
                                "season_id": 28,
                                "top_rank_position": 0
                            },
                            "season_statistics": {
                                "deaths": 0,
                                "kills": 0,
                                "match_outcomes": {
                                    "abandons": 0,
                                    "losses": 0,
                                    "wins": 0
                                }
                            }
                        }
                    ]
                },
                {
                    "board_id": "event",
                    "full_profiles": [
                        {
                            "profile": {
                                "board_id": "event",
                                "id": "REMOVED",
                                "max_rank": 0,
                                "max_rank_points": 0,
                                "platform_family": "pc",
                                "rank": 0,
                                "rank_points": 0,
                                "season_id": 28,
                                "top_rank_position": 0
                            },
                            "season_statistics": {
                                "deaths": 0,
                                "kills": 0,
                                "match_outcomes": {
                                    "abandons": 0,
                                    "losses": 0,
                                    "wins": 0
                                }
                            }
                        }
                    ]
                },
                {
                    "board_id": "warmup",
                    "full_profiles": [
                        {
                            "profile": {
                                "board_id": "warmup",
                                "id": "REMOVED",
                                "max_rank": 0,
                                "max_rank_points": 0,
                                "platform_family": "pc",
                                "rank": 0,
                                "rank_points": 0,
                                "season_id": 28,
                                "top_rank_position": 0
                            },
                            "season_statistics": {
                                "deaths": 0,
                                "kills": 0,
                                "match_outcomes": {
                                    "abandons": 0,
                                    "losses": 0,
                                    "wins": 0
                                }
                            }
                        }
                    ]
                },
                {
                    "board_id": "ranked",
                    "full_profiles": [
                        {
                            "profile": {
                                "board_id": "ranked",
                                "id": "REMOVED",
                                "max_rank": 1,
                                "max_rank_points": 1080,
                                "platform_family": "pc",
                                "rank": 1,
                                "rank_points": 1080,
                                "season_id": 28,
                                "top_rank_position": 0
                            },
                            "season_statistics": {
                                "deaths": 3,
                                "kills": 1,
                                "match_outcomes": {
                                    "abandons": 0,
                                    "losses": 0,
                                    "wins": 1
                                }
                            }
                        }
                    ]
                }
            ],
            "platform_family": "pc"
        }
    ]
}
```
</details>

---
Another one for profiles would be
`https://public-ubiservices.ubi.com/v2/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/title/r6s/skill/detailed_ranked_profile`

this needs `platform_family` (notice it's singular here!) and `nb_past_seasons` params to be specified
<details><summary>Response</summary>

```json
{
    "archived_profiles": [],
    "full_profile": {
        "profile": {
            "board_id": "ranked",
            "id": "REMOVED",
            "max_rank": 1,
            "max_rank_points": 1080,
            "platform_family": "pc",
            "rank": 1,
            "rank_points": 1080,
            "season_id": 28,
            "top_rank_position": 0
        },
        "season_statistics": {
            "deaths": 3,
            "kills": 1,
            "match_outcomes": {
                "abandons": 0,
                "losses": 0,
                "wins": 1
            }
        }
    },
    "last_ranked_game_information": {
        "has_abandoned": false,
        "rank_points_update": {
            "demotion_shield_rank_points_saved": 0,
            "rank_points_after": 1080,
            "rank_points_before": 1000
        },
        "team_score": 1
    }
}
```
</details>

---
EDIT:
<details><summary>Headers used</summary>

- `ubi-appid`: `e3d5ea9e-50bd-43b7-88bf-39794f4e3d40`
- `ubi-appbuildid`: `Y7S4.1_C7296873_D1550531_S49485_48690975_PROD`
- `Authorization`: `Ubi_v1 t=YOUR-ENCODED-TICKET`
- `Ubi-localeCode`: `en-US`
- `ubi-populations`: `BattlePassSyncState.V2_Preconfirmed,BattlePassUI.Enabled,BinaryDistribution.Enabled,CommunityEvent.Live,DebugCamera.Disabled,GamePlay.FullPopulation,HighFrequencyEvents.NoSend,IsRecommenderServiceEnabled.RecommenderServiceEnabled,PopulationBasedChallenges.Group0,QC.LiveConfig,RemoteLogsV2.ByDefault,tg_CrashReport.UploadReport,Watermark.Enabled`
- `ubi-sessionid`: `YOUR-SESSION-GUID`
- `User-Agent`: `UbiServices_SDK_2020.Release.58_PC64_ansi_static`
</details>

Not all of the above are required.

**Comment by floxay** [comment]
Additionally, here's a (low-effort) list:
<details><summary>Click</summary>

```
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6cloudservers/datacenters
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6commerce/products?locale_code=%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6config/client_config
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6endgame/bp_challenges_status/me?challenge_ids=%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6endgame/end_game_results
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions?player=%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions/%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions/%s/members/me
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions/%s/messages/broadcast
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6party/sessions/%s/messages/send
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6pbjournal/external_player_report
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6penalties/active_penalties
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6rewards/disable_all_boosters
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6rewards/enable_
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6rewards/players_active_boosters_for_game?team1_profile_ids=%s&team2_profile_ids=%s&session_type=%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6rewards/players_active_boosters?profile_ids=%s
/v1/spaces/{spaceID}/sandboxes/{sandboxID}/r6store/client_privileges
/v1/spaces/{spaceID}/title/r6s/battlepasses
/v1/spaces/{spaceID}/title/r6s/binary-distribution/player/me/status/%s/%s/%s
/v1/spaces/{spaceID}/title/r6s/gs-allocator/datacenters
/v1/spaces/{spaceID}/title/r6s/party/players/%s/membership
/v1/spaces/{spaceID}/title/r6s/party/players/me/membership
/v1/spaces/{spaceID}/title/r6s/products?locale_code=%s
/v1/spaces/{spaceID}/title/r6s/profiles/me/active_penalties
/v1/spaces/{spaceID}/title/r6s/profiles/me/migration?sandbox=%s
/v1/spaces/{spaceID}/title/r6s/profiles/me/privileges
/v1/spaces/{spaceID}/title/r6s/reconnect/profiles/me/reservations?match_types=%s
/v1/spaces/{spaceID}/title/r6s/reconnect/profiles/me/reservations/%s
/v1/spaces/{spaceID}/title/r6s/rewards/prepare_match?match_unique_id=%s&session_type=%s
/v1/spaces/{spaceID}/title/r6s/rewards/public_profile?profile_id=%s
/v1/spaces/{spaceID}/title/r6s/vivox/join-token?domain=%s&channel=%s
/v1/spaces/{spaceID}/title/r6s/vivox/login-information?domain=%s
/v1/spaces/{spaceID}/title/r6s/vivox/transcription-token?domain=%s&channel=%s
/v2/spaces/{spaceID}/sandboxes/{sandboxID}/r6vivox/join_
/v2/spaces/{spaceID}/sandboxes/{sandboxID}/r6vivox/login_information
/v2/spaces/{spaceID}/sandboxes/{sandboxID}/r6vivox/transcription_token
/v2/spaces/{spaceID}/title/r6s/skill/
/v2/spaces/{spaceID}/title/r6s/skill/detailed_ranked_profile?nb_past_seasons=%s&platform_family=%s
/v2/spaces/{spaceID}/title/r6s/skill/full_profiles?profile_ids=%s&platform_families=%s
/v2/spaces/{spaceID}/title/r6s/skill/update_display?platform_family=%s
```
</details>

**Comment by SwiftCODA** [comment]
> use `/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/sandboxes/OSBOR_XPLAY_LNCH_A/`
> 
> ![image](https://user-images.githubusercontent.com/57007485/209000063-18b8b66b-66b9-46e5-8caf-b30dc929a9e9.png)

What is the full path and parameters and headers that you're using here? I keep getting stripped in prod errors.

**Comment by SwiftCODA** [comment]
> > use `/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/sandboxes/OSBOR_XPLAY_LNCH_A/`
> 
> This looks like an old ranked system running in parrallel with ranked 2.0. I played 9 ranked matches and my rank is still zero (unranked), but I'm Copper 3 in terms of ranked 2.0. Literally yesterday I discovered that there's a new spaceId for crossplay.
> 
> UPD: Confirmed. After 10th game I got Silver 3 with 2340 MMR. Just like the good old days.

Did it update after 10 matches or after a time period?

**Comment by SwiftCODA** [comment]
@floxay 
<img width="1014" alt="Screenshot 2022-12-23 at 1 44 38 AM" src="https://user-images.githubusercontent.com/17557339/209313010-4a6a648c-48d5-4fa5-958f-4dec9229802c.png">

Using your headers and parameters.

**Comment by aspriddell** [comment]
I got this as well @SwiftCODA, if you re-authenticate but use the pc client app-id (`e3d5ea9e-50bd-43b7-88bf-39794f4e3d40`), the ticket you get should work properly. (edit: you'll need to keep two tickets working, one using the old app-id for the pre-existing urls and this one for the ones you're hitting errors with)

As for some other things I noticed, the `full_profiles` endpoint allows you to put any profile in and get data back but I found that `detailed_ranked_profile` only returned my profile ~~(and only wanted the `nb_past_seasons` parameter)~~. Neither of those two return previous seasons' information which is in line with what [TRN has said](https://tracker.gg/r6siege/articles/solar-raid-update-1#:~:text=Ubisoft%20API%20Restrictions)

**Comment by SwiftCODA** [comment]
> (edit: you'll need to keep two tickets working, one using the old app-id for the pre-existing urls and this one for the ones you're hitting errors with)

Used the new appId, getting a good response now. However, on multiple profileIds, the data returned is basically zeroed out, all default stuff, even though TRN shows that the players have rank points, kills, etc.

**Comment by SwiftCODA** [comment]
> (and only wanted the `nb_past_seasons` parameter).

@aspriddell 
<img width="934" alt="Screenshot 2022-12-23 at 10 34 05 PM" src="https://user-images.githubusercontent.com/17557339/209424590-e640df73-7f0a-4d95-91d8-1a0c8ba4f5e2.png">

Need platform_family too. But you're right, it doesn't call for any profile_ids. Just returns data for the profile_id associated with the ticket.

**Comment by floxay** [comment]
`profile_ids` param for `/detailed_ranked_profile` was an error on my part, probably left it there by accident when I copied the first endpoint's text, edited my comment above.

**Comment by SwiftCODA** [comment]
> > (edit: you'll need to keep two tickets working, one using the old app-id for the pre-existing urls and this one for the ones you're hitting errors with)
> 
> Used the new appId, getting a good response now. However, on multiple profileIds, the data returned is basically zeroed out, all default stuff, even though TRN shows that the players have rank points, kills, etc.

Still unsure of above... Help is appreciated.

All responses I'm getting with the new spaceId path give me zeroed-out information, or "default" data. For example:
https://pastebin.com/kBYEsi1q
Using the headers:
<img width="1358" alt="Screenshot 2023-01-03 at 10 25 38 PM" src="https://user-images.githubusercontent.com/17557339/210496451-d136bb4d-f820-462f-a351-b44428fdaba5.png">
<img width="1288" alt="Screenshot 2023-01-03 at 10 25 47 PM" src="https://user-images.githubusercontent.com/17557339/210496462-da2fe34b-b742-421a-b042-66fc8ba73690.png">



@floxay @aspriddell @BadCoder1337

**Comment by aspriddell** [comment]
@SwiftCODA I've tried using the same headers you have and I can get some proper stats back.

![image](https://user-images.githubusercontent.com/10289119/210533267-4343c339-a5a9-41ba-819f-4553218a5ff4.png)

I also did a check on the profile id you're using and also found it comes back blank. Does the id belong to a console account? I wouldn't be surprised if `profile_ids` is now misleading and it wants a set of ubisoft ids instead... (and all the ids I used have the same profile and ubisoft id)

**Comment by SwiftCODA** [comment]
>  I also did a check on the profile id you're using and also found it comes back blank. Does the id belong to a console account? I wouldn't be surprised if `profile_ids` is now misleading and it wants a set of ubisoft ids instead... (and all the ids I used have the same profile and ubisoft id)

I recall the profileId I used above being one belonging to a random leaderboard champion player, not sure which platform.
For further testing, I am using the below information obtained from the below endpoint:
<img width="674" alt="Screenshot 2023-01-04 at 10 46 40 AM" src="https://user-images.githubusercontent.com/17557339/210627768-15df4097-4ea2-4c21-b9f9-561d388ff17b.png">
<img width="500" alt="Screenshot 2023-01-04 at 10 46 34 AM" src="https://user-images.githubusercontent.com/17557339/210627777-94ffe7d8-f8c5-49fe-b0ff-02dda8bcf91b.png">

You can see the profileId and userId are only the same when the account is a uplay/pc account.

When using the new `OSBOR_XPLAY_LNCH_A` path, I get data when passing in a _**uplay**_ profileId (the account's userId). Since the userId is synchronous between all sub-accounts on all platforms tied to a single Ubisoft account, the data returned should respect cross-progression. 

Here, I use the `userId` shown above, in place of the profile_ids query param:
<img width="850" alt="Screenshot 2023-01-04 at 10 52 18 AM" src="https://user-images.githubusercontent.com/17557339/210628321-48fa6ae0-30dd-42a0-af8b-47299c97cddb.png">
<img width="474" alt="Screenshot 2023-01-04 at 10 53 08 AM" src="https://user-images.githubusercontent.com/17557339/210628444-bbb2ed87-7dd3-4382-8b6c-211a3f67fb81.png">

However, if you visit either:
- https://r6.tracker.network/profile/xbox/Lessthan69
- https://r6.tracker.network/profile/pc/yeetusmx
they show the same level, which at the time of writing this, is 32, which does not match the response I got.

**Comment by floxay** [comment]
`/v1/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/title/r6s/rewards/public_profile?profile_id=596a2b47-3df6-4c08-aa2c-5450f40900ae`

```json
{
    "level": 32,
    "xp": 7671
}
```

**Comment by SwiftCODA** [comment]
@floxay You are an absolute g. ❤️💪

**Comment by SwiftCODA** [comment]
Closing #91 with the following new information for developers:
This issue contains a large amount of information regarding new endpoints for Ubisoft's Rainbow Six: Siege stats service.
New endpoint data includes:
- Rank points
- Ranked 2.0 rank system
- Ranked/Casual
- Level/XP
- Season 28 data (not preserved when future seasons release, as of now).

A big thank you to all contributors in this thread! Good luck with your projects, everyone.
