### ISSUE TITLE
Op Stats for Ranked 2.0 (Y7S4+)

### ISSUE THREAD

**Issue by SwiftCODA** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#92]
Has anyone had any luck finding usable endpoints for operator stats after Y7S3?

The existing endpoint for operator stats is incredibly annoying and has stopped updating as of the beginning of Y7S4.

**Comment by byterip** [comment]
Which operator stats specifically are you searching for?

**Comment by SwiftCODA** [comment]
> Which operator stats specifically are you searching for?

Basic stuff, like for a player, how many kills, deaths, wins, losses, time played they have with each operator.

The endpoint exposed on the Ubisoft R6 Stats Tracker site shows op stats only dating back to Y6S1. EDIT: This endpoint also shows Y7S4+ op stats too, but nothing from Y5S4 or older.

The endpoint also has very severe rate limiting.
