### ISSUE TITLE
Y8S3 Heavy Mettle Ranked Stats

### ISSUE THREAD

**Issue by SwiftCODA** [Seems2Legit/Rainbow-Six-Siege-Player-Stats-API#94]
Does anyone have an endpoint for "current season" stats for the new season?
Previously we were using: 
`https://public-ubiservices.ubi.com/v2/spaces/0d2ae42d-4c27-4cb7-af6c-2099062302bb/title/r6s/skill/full_profiles?platform_families=pc,console&profile_ids={USER_ID}`

This seems to be returning a 404 now...

Is there a new endpoint or spaceId?

**Comment by SwiftCODA** [comment]
This profile should have data according to TRN...

<img width="827" alt="Screenshot 2023-08-30 at 9 28 47 PM" src="https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/assets/17557339/1e543313-3b01-4f5d-85b1-63a275cfe2c8">
<img width="897" alt="Screenshot 2023-08-30 at 9 28 26 PM" src="https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/assets/17557339/f11e2edf-08e7-44be-a414-a04abf56a393">

**Comment by SwiftCODA** [comment]
@Barcelona @JulianGassner @Pheromir @sidelux @danielwerg @SamWinterhalder @Gunale0926 @BadCoder1337 @redraskal @Digneety

**Comment by BadCoder1337** [comment]
Looks like a new endpoint. Checked `lastPlayed` endpoint, no new `spaceId` was introduced.

**Comment by floxay** [comment]
Just wait until at least the game itself is working? (Ubi moment)
![image](https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/assets/57007485/d16970e0-ce9d-4f3b-9997-ecb20b60457d)
![image](https://github.com/Seems2Legit/Rainbow-Six-Siege-Player-Stats-API/assets/57007485/545f119a-4990-4dbf-b976-21d7a12d90ca)

**Comment by SwiftCODA** [comment]
> Looks like a new endpoint. Checked `lastPlayed` endpoint, no new `spaceId` was introduced.

What's the full endpoint? I'm not sure this is the equivalent...

**Comment by floxay** [comment]
> Just wait until at least the game itself is working? (Ubi moment)
![image](https://user-images.githubusercontent.com/57007485/264783276-545f119a-4990-4dbf-b976-21d7a12d90ca.png)

It's back now.
